# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'ingresspool'
  demands:
    - agent.name -equals ingressagent

stages:
  - stage: DeployKubernetes
    displayName: DeployKubernetes
    jobs:
      - job: PublishArtifactstoPipeline
        displayName: PublishArtifactstoPipeline
        steps:
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)'
              artifact: 'allfiles'
              publishLocation: 'pipeline'
          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'agiccon'
              azureResourceGroup: 'agicdemo'
              kubernetesCluster: 'agic-cluster'
              namespace: 'default'
              manifests: '$(System.DefaultWorkingDirectory)/kube-manifests'
          